### PR TITLE
CircleCI Docker image supports antora builds

### PR DESCRIPTION
**Pull request by alandefreitas**
Updates CircleCI Docker image to `cppalliance/boost_superproject_build:20.04-v3`, which includes nodejs.

### CODE REVIEW

**Comment by alandefreitas** [comment]
@sdarwin

**Comment by alandefreitas** [comment]
@pdimov

**Comment by pdimov** [comment]
After merging this PR jobs fail with

```
Starting container cppalliance/boost_superproject_build:20.04-v3
Warning: No authentication provided, using CircleCI credentials for pulls from Docker Hub.
  image cache not found on this host, downloading cppalliance/boost_superproject_build:20.04-v3

Error response from daemon: manifest for cppalliance/boost_superproject_build:20.04-v3 not found: manifest unknown: manifest unknown
```

https://app.circleci.com/pipelines/github/boostorg/boost/10544/workflows/9c3afb33-9127-49be-85f1-858be261b82e/jobs/25277

**Comment by sdarwin** [comment]
Should be fixed. Check the next builds.

**Pull request merged**
