### PR TITLE
Remove signals (1st gen) - deprecated since 1.54.0 - announced 1.68.0 - removed 1.69.0

### PR DESCRIPTION
**Pull request by jeking3**

### CODE REVIEW

**Comment by jeking3** [comment]
@mjcaisse please kick the build again (or the individual jobs that failed) looks like environmental issues.

**Comment by glenfe** [comment]
We committed to doing this for 1.69, so here goes.

**Comment by glenfe** [comment]
If there are no issues or once any issues are resolved, I'll take care of merging this to master.

**Comment by jeking3** [comment]
This needs a release note as well.

**Comment by glenfe** [comment]
Already planned, including a heartfelt thank you to Doug for his contribution in the release notes.

**Pull request merged**
