### PR TITLE
Automatically build tool docs also.

### PR DESCRIPTION
**Pull request by grafikrobot**
Corresponding change to https://github.com/boostorg/boost/commit/6bc65435dc18e5d4c64cd43cac6779a903cc3edd

### CODE REVIEW

**Comment by mclow** [comment]
This looks fine to me.

**Comment by mclow** [comment]
Whoops. This should go into `develop`, right?

**Comment by jeking3** [comment]
Shouldn't we always be merging develop into master, not picking things?

**Comment by pdimov** [comment]
https://github.com/boostorg/boost/commit/36b81c46be50588e599a498c4d2261da3b0f8ab2

**Comment by jeking3** [comment]
So this can be closed?

**Comment by pdimov** [comment]
I cherry-picked the develop commit before realizing I could just have merged the PR.

**Pull request closed without merging**
