### PR TITLE
Added vmd submodule

### PR DESCRIPTION
**Pull request by eldiener**

### CODE REVIEW

**Comment by danieljames** [comment]
It will also need to added to status/Jamfile.v2 to start testing, but it's probably best to wait until the release is out, as they're sorting out some issue with the build system.

**Comment by danieljames** [comment]
I changed it to the develop branch: 19f4bfb613f2e31f5576d337f70ceac7f265fe92

**Comment by eldiener** [comment]
What is status/Jamfile.v2 about ? I do have a jamfile.v2 in the test directory.

**Comment by swatanabe** [comment]
AMDG

On 04/03/2015 09:14 AM, Edward Diener wrote:
> What is status/Jamfile.v2 about ? I do have a jamfile.v2 in the test directory.
> 

status/Jamfile.v2 is the global list of tests used
by the regression testing system.  It should probably
be updated to use a glob, so we don't have to go
through this every time a new library is added.

In Christ,
Steven Watanabe

**Pull request merged**
