### PR TITLE
Add quickbook to status/Jamfile

### PR DESCRIPTION
**Pull request by pdimov**

### CODE REVIEW

**Comment by pdimov** [comment]
Yes, it seems that there's something in Quickbook's test Jamfile that breaks --dump-tests. I'm trying to figure out what.

**Comment by pdimov** [comment]
Pretty sure it's this thing

```
    modules.poke testing : .all-tests : \$\(all-tests\) $(t) ;
```

not yet positive on why it doesn't work and how it needs to be fixed. :-)

**Comment by Kojoley** [comment]
Yes, I was looking at this too. Removing them fixes the problem.

**Comment by Kojoley** [comment]
`modules.poke testing : .all-tests : [ modules.peek testing : .all-tests ] $(t) ;` solves the problem.

**Comment by pdimov** [comment]
I'm pretty sure that this needs to be something like

```
    local all-tests = [ modules.peek testing : .all-tests ] ;
    all-tests += $(t) ;
    modules.poke testing : .all-tests : $(all-tests) ;
```

What I'm not sure about though is whether the `QUICKBOOK_OUTPUT` tests need to be added to `.all-tests`.

**Comment by pdimov** [comment]
Crossed the streams. :-)

**Comment by Kojoley** [comment]
> What I'm not sure about though is whether the `QUICKBOOK_OUTPUT` tests need to be added to `.all-tests`.

I guess no, `testing` does not add `RUN_OUTPUT` targets to `.all-tests`. It looks like `QUICKBOOK_OUTPUT`  is just a remake of `make` rule.

**Comment by pdimov** [comment]
https://github.com/boostorg/quickbook/pull/3

**Pull request merged**
