### PR TITLE
Added VMD library

### PR DESCRIPTION
**Pull request by eldiener**

### CODE REVIEW

**Comment by eldiener** [comment]
Since I made a pull request to add the VMD library to boost on the 'develop' branch and supposedly the Travis CI build succeeded there it makes little sense to me that adding the VMD library on the 'master' branch causes Travis CI to fail. Is there any indication about why that has happened ?

**Comment by danieljames** [comment]
If you click on 'Details' to the right of the failure message you can see the error. Looks like the build isn't correctly set up, so it's probably nothing to do with you.

But you shouldn't be creating a pull request for master until everything is fine on develop (tests. documentation, etc.). Same as we used to do on subversion.

**Comment by eldiener** [comment]
I can close this pull request until everything is fine on develop. However isn't this going to lead to the same situation of which I complained regarding the 'sync' library, where there was only a 'develop' branch and anyone wishing to do a 'git submodule foreach --recursive git checkout master' would be stopped by a lack of a 'master' branch for VMD ?

**Comment by eldiener** [comment]
I see my mistake and will close this pull request.

**Pull request closed without merging**
