### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by BeErikk**
ignore 64-bit stage directory - add to .gitignore

`index 231a4508f..91ae80b13 100644
--- a/.gitignore
+++ b/.gitignore
@@ -7,7 +7,7 @@
 /boost
 /dist
 /project-config.jam*
-/stage
+/stage*
 /user-config.jam
 /.settings/
 /.project`

edit 
hmm lol - "BeErikk  wants to merge 10,000 commits into master from develop"
No I don't, just the above patch

### CODE REVIEW

**Comment by danieljames** [comment]
You branched from develop, so you need to make to pull request against develop.

**Comment by BeErikk** [comment]
@danieljames

Thanks. How to fix it now?

**Comment by danieljames** [comment]
We use trac for bug reports/feature requests:

https://svn.boost.org/trac10/newticket

Or you can open a pull request by editing the file here:

https://github.com/boostorg/boost/blob/develop/.gitignore

Just click on the pencil icon at the top right of the code.

I'm not keen on the change though, it seems like the pattern could accidentally match other things. Perhaps we could use a more specific pattern. What's the name of directory you want to ignore?

**Comment by BeErikk** [comment]
Hello Daniel
The directory is `stage_x64`. I see now that this directory was created by a external building script for b2 to build 64-bit with VS2017, which at least was a bit of a challenge. So, your right and I'm sorry for the fuzz. close this

**Comment by danieljames** [comment]
I'll add an ignore for `stage_x64`, that's no problem.

**Pull request closed without merging**
