### PR TITLE
Change encoding to UTF-8 for minimal.css

### PR DESCRIPTION
**Pull request by jwakely**
CSS files should be UTF-8: https://www.w3.org/International/questions/qa-css-charset

### CODE REVIEW

**Comment by jwakely** [comment]
https://github.com/boostorg/filesystem/commit/9df2bfab58aadf35b4e01f2fd6252e1521409779#diff-36873c6a5a238ba4df45a47d97d80ead5ed664b3cb7e5a8fbe918020cc6889a4 replaced another ISO-8859-1 copyright symbol with `(c)`, which would also be an option here. I just want to get rid of the ISO-8859-1 character in a file that doesn't specify its `@charset`, because it causes warnings for distro packagers.

**Comment by mclow** [comment]
I think changing to '(c)' is the simplest fix.

**Comment by jwakely** [comment]
OK thanks, I'll re-push with that change then...

**Comment by jwakely** [comment]
Now done consistently with https://github.com/boostorg/detail/commit/8c603a1894ec1d8abc7a0a538297923b0ac98b33

**Comment by jwakely** [comment]
Ping

**Pull request merged**
